name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.22'

    - name: Build
      run: go build -v ./...

    - name: Test & Coverage
      run: |
        go test -v ./... -coverprofile coverage.out -coverpkg=./...
        go tool cover -func=coverage.out
    
    - name: Benchmark
      run: go test -bench=. -benchmem -run=XXX # run parameter disables non-benchmarking tests in this run
